# Generated by Django 4.1.2 on 2022-10-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.category')),
            ],
            options={
                'verbose_name': 'Одиниця',
                'verbose_name_plural': 'Одиниці',
            },
        ),
        migrations.CreateModel(
            name='ItemCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('items', models.ManyToManyField(to='checker.item', verbose_name='Елементи')),
            ],
            options={
                'verbose_name': 'Покриття',
                'verbose_name_plural': 'Покриття',
            },
        ),
        migrations.CreateModel(
            name='ItemPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('paper_width', models.IntegerField(verbose_name='Щільність паперу')),
                ('description', models.CharField(max_length=300, verbose_name='Опис')),
                ('items', models.ManyToManyField(to='checker.item', verbose_name='Елементи')),
            ],
            options={
                'verbose_name': 'Папір',
                'verbose_name_plural': 'Папір',
            },
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Назва')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Висота')),
                ('items', models.ManyToManyField(to='checker.item', verbose_name='Елементи')),
            ],
            options={
                'verbose_name': 'Розмір',
                'verbose_name_plural': 'Роміри',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150, verbose_name='Посада')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамілія')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.position', verbose_name='Посада')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(max_length=700, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(verbose_name='Статус')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.itemcover', verbose_name='Папір')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='checker.user', verbose_name='Дизайнер')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.item', verbose_name='Елемент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='checker.user', verbose_name='Менеджер')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.itempaper', verbose_name='Папір')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.itemsize', verbose_name='Розмір')),
            ],
        ),
    ]
