# Generated by Django 4.1.2 on 2022-10-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Посада', 'verbose_name_plural': 'Посади'},
        ),
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Зворот'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Лице'),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва'),
        ),
    ]
