# Generated by Django 4.1.2 on 2022-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_alter_position_options_product_back_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статуси',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.AlterField(
            model_name='itempaper',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Опис'),
        ),
    ]
