# Generated by Django 4.1.2 on 2022-10-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsize',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='checker.itemsize', verbose_name='Розмір'),
        ),
    ]
