# Generated by Django 4.1.2 on 2022-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_remove_item_size_itemsize_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsize',
            name='items',
        ),
        migrations.AddField(
            model_name='itemsize',
            name='items',
            field=models.ManyToManyField(null=True, to='checker.item', verbose_name='Елемент'),
        ),
    ]
