# Generated by Django 4.1.2 on 2022-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_remove_itemsize_items_itemsize_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='items',
            field=models.ManyToManyField(to='checker.item', verbose_name='Елемент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=700, null=True, verbose_name=''),
        ),
    ]
