# Generated by Django 4.1.2 on 2022-11-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_product_quantity_alter_itemsize_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='checker.user', verbose_name='Дизайнер'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.user', verbose_name='менеджер')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.manager', verbose_name='Менеджер'),
        ),
    ]
