# Generated by Django 4.1.2 on 2022-11-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_alter_product_designer_manager_alter_product_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AlterField(
            model_name='product',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.manager', verbose_name='Менеджер'),
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.user', verbose_name='дизайнер')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.designer', verbose_name='Дизайнер'),
        ),
    ]
