# Generated by Django 4.1.2 on 2022-11-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_delete_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manager',
        ),
    ]
