# Generated by Django 4.1.2 on 2022-11-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_remove_product_designer_remove_product_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.designer', verbose_name='Дизайнер'),
        ),
        migrations.AddField(
            model_name='product',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.manager', verbose_name='Менеджер'),
        ),
    ]
