# Generated by Django 4.1.2 on 2022-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_alter_designer_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Зворот'),
        ),
    ]
