# Generated by Django 4.1.2 on 2022-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0015_product_back_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='front_smaller_image',
            new_name='back_thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='front_thumbnail',
            field=models.ImageField(null=True, upload_to='img/smaller', verbose_name='Лице міні'),
        ),
    ]
