# Generated by Django 4.1.2 on 2022-12-05 08:46

import checker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0016_rename_front_smaller_image_product_back_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image',
            field=models.ImageField(null=True, upload_to=checker.models.product_directory_path, verbose_name='Зворот'),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_thumbnail',
            field=models.ImageField(null=True, upload_to=checker.models.thumbnail_directory_path, verbose_name='Зворот мініатюра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image',
            field=models.ImageField(null=True, upload_to=checker.models.product_directory_path, verbose_name='Лице'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_thumbnail',
            field=models.ImageField(null=True, upload_to=checker.models.thumbnail_directory_path, verbose_name='Лице мініатюра'),
        ),
    ]
