# Generated by Django 4.1.2 on 2022-12-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0019_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='checker.user', verbose_name='дизайнер'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='checker.user', verbose_name='менеджер'),
        ),
    ]
