# Generated by Django 4.1.2 on 2022-12-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0021_user_category_alter_product_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='checker.user', verbose_name='дизайнер'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='checker.user', verbose_name='менеджер'),
        ),
    ]
