# Generated by Django 4.1.2 on 2022-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0024_item_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cut_size',
            field=models.SmallIntegerField(null=True, verbose_name='Розмір порізки'),
        ),
    ]
