# Generated by Django 4.1.2 on 2022-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0025_category_cut_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcover',
            name='in_stock',
            field=models.BooleanField(default=True, null=True, verbose_name='В наявності'),
        ),
        migrations.AddField(
            model_name='itempaper',
            name='in_stock',
            field=models.BooleanField(default=True, null=True, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='itempaper',
            name='paper_width',
            field=models.IntegerField(verbose_name='Щільність матеріалу'),
        ),
    ]
